global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']

  - job_name: 'callback'
    static_configs:
      - targets: ['callback:3000']

  - job_name: 'ledger-worker'
    static_configs:
      - targets: ['ledger-worker:3000']  

  - job_name: 'bet-resolver'
    static_configs:
      - targets: ['bet-resolver:3000']