services:
  bet-resolver:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - kafka
      - callback
    environment:
      - KAFKA_BROKERS=kafka:9093
      - CALLBACK_URL=http://callback:3000/callback
    restart: unless-stopped
